Svgr additional options
marcomontalbano/figma-export pull request #114
Opened 2022-03-10 16:23 UTC by inspiratweb

Adding a proposal for solving this: https://github.com/marcomontalbano/figma-export/issues/112

2022-03-10 21:51 UTC, marcomontalbano requested changes
Hi @inspiratweb, thanks a lot for this proposal. I made few changes just to keep `options` argument as mandatory to avoid breaking-changes.

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/README.md
> +    getExportTemplate = (): string => '',
```suggestion
    getExportTemplate = (options): string => {
        const reactComponentName = getComponentName(options);
        const reactComponentFilename = `${reactComponentName}${getFileExtension(options)}`;
        return `export { default as ${reactComponentName} } from './${reactComponentFilename}';`;
    },
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.test.ts
> +            getExportTemplate: (options) => `export { ${options!.basename} } from './customPath';`,
```suggestion
            getExportTemplate: (options) => `export { ${options.basename} } from './customPath';`,
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +    getExportTemplate?: (options?: FigmaExport.ComponentOutputterParamOption) => string;
`options` should be always set.

```suggestion
    getFileExtension?: (options: FigmaExport.ComponentOutputterParamOption) => string;
    getExportTemplate?: (options: FigmaExport.ComponentOutputterParamOption) => string;
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +
```suggestion
    getExportTemplate = (options): string => {
        const reactComponentName = getComponentName(options);
        const reactComponentFilename = `${reactComponentName}${getFileExtension(options)}`;
        return `export { default as ${reactComponentName} } from './${reactComponentFilename}';`;
    },
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
>      [key: string]: string[];
```suggestion
    [key: string]: {
        exports: string[]
        ext: string
    };
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +    const indexFormat = getFileExtension() === '.tsx' ? '.ts' : '.js';
I would move this below, so that I can call `getFileExtension` with `options`.

```suggestion
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +                const exportTemplate = getExportTemplate(options) || `export { default as ${reactComponentName} } from './${basename}';`;
```suggestion
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +                indexFile[filePath].push(exportTemplate);
```suggestion
                indexFile[filePath] = indexFile[filePath] || {
                    ext: getFileExtension(options) === '.tsx' ? '.ts' : '.js',
                    exports: [],
                };
                indexFile[filePath].exports.push(getExportTemplate(options));
```

2022-03-10 21:51 UTC, marcomontalbano commented on packages/output-components-as-svgr/src/index.ts
> +                fs.writeFileSync(path.resolve(filePath, `index${indexFormat}`), exports.join('\n'));
```suggestion
            Object.entries(indexFile).forEach(([filePath, index]) => {
                fs.writeFileSync(path.resolve(filePath, `index${index.ext}`), index.exports.join('\n'));
```

2022-03-11 16:42 UTC, inspiratweb commented
Thank you so much!
I've tested it and it works like a charm

2022-03-12 21:44 UTC, marcomontalbano approved these changes

2022-03-12 21:44 UTC, merged